name: StoreNetNg-CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4.2.0
        with:
         node-version: "19"
      - name: Install deps
        run: npm i
      - name: Build app bundle
        run: npm run build:prod
      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/store-net-ng/browser
        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
